spring:
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jotang
    username: root
    password: 1234
    #文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#阿里云oss
aliyun:
  oss:
    endpoint: https://oss-cn-heyuan.aliyuncs.com
    accessKeyId: LTAI5tN9TxMKvY1cQLrqt6zy
    accessKeySecret: oJayvGwQLLT5bhan6akJTdCMAqKCyX
    bucketName: jotang
